target-version = "py311"

[lint]
select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "B",   # flake8-bugbear
    "I",   # isort
    "D",   # pydocstyle
    "W",   # pycodestyle warnings
    "C4",  # flake8-comprehensions (idiomatic collections)
    "FIX", # fixme
    "FA",  # future-annotation
    "LOG", # logging
    "INP", # PEP420
    "PIE", # flake8-pie
    "PLC", # pylint convention
    "PLE", # pylint error
    "PLW", # pylint warning
    "RET", # flake8-return
    "RSE", # flake8-raise
    "RUF", # Ruff-specific rules
    "SIM", # flake8-simplify (simplify code)
    "UP",  # pyupgrade (modernize syntax)
    "YTT", # flake8-2020
]

# Ignored rules
ignore = [
    "E501", # line-too-long
    "I001", # unsorted-imports
    "D205", # blank-line-after-summary
    "D402", # no-signature
    "D415", # ends-in-punctuation
    "D417", # undocumented-param
]


[lint.per-file-ignores]

[lint.isort]
known-first-party = []
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
force-sort-within-sections = false

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "preserve"
