[project]
name = "python-update-checker"
version = "1.4.0"
readme = "README.md"
requires-python = ">=3.11"
license = "GPL-3.0-only"
# https://pypi.org/classifiers/
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development :: Build Tools",
]
dependencies = [
  # track compatibility, do not pin
  "packaging>=26.1",
]
license_files = [
  "COPYING",
]

[project.urls]
Changelog = "https://github.com/wummel/python-update-checker/blob/main/CHANGELOG.md"
Homepage = "https://github.com/wummel/python-update-checker"
Issues = "https://github.com/wummel/python-update-checker/issues"
Repository = "https://github.com/wummel/python-update-checker.git"

[project.scripts]
puc = "puc:cli.main"

[dependency-groups]
# these packages are only needed for development
dev = [
  # for upgrading the version number
  "bump2version==1.0.1",
  # for testing
  "pytest==9.1.1",
  # for python code linting
  "ruff==0.16.6",
  # Markdown style checking and formatting
  "rumdl==0.2.69",
  # reformat toml files
  "tombi==1.5.4",
  # for python type checking
  "ty==0.0.79",
  # for auditing github actions
  "zizmor==1.30.1",
]

[build-system]
requires = ["uv_build>=0.11.32,<0.13"]
build-backend = "uv_build"

[tool.project]
# pin versions of Python and uv for development
python_version_dev = "3.14.7"
uv_version_dev = "0.12.15"

[tool.uv.build-backend]
module-name = "puc"
source-include = [
  ".gitignore",
  ".ruff.toml",
  "Makefile",
  "scripts/**",
  "tests/**",
]
